### ISSUE TITLE
Dev build not working on Windows (yarn dev)

### ISSUE THREAD

**Issue by rocodesign** [codeBelt/hapi-react-hot-loader-example#21] opened 2017-08-28 15:23 UTC
Hi

I got the latest version of the project
ran 
yarn
yarn dev

I see the logs:

`
$ cross-env npm run removeAndBuildServer

> hapi-react-hot-loader-example@1.0.0 removeAndBuildServer D:\Work\rococode\reacthotloader
> cross-env npm run remove && npm run buildServer

> hapi-react-hot-loader-example@1.0.0 remove D:\Work\rococode\reacthotloader
> cross-env rimraf dist

> hapi-react-hot-loader-example@1.0.0 buildServer D:\Work\rococode\reacthotloader
> cross-env BABEL_ENV=server ./node_modules/.bin/babel src --out-dir dist

src\client.jsx -> dist\client.js
src\RouterWrapper.jsx -> dist\RouterWrapper.js
src\server\controllers\AssetsController.js -> dist\server\controllers\AssetsController.js
src\server\controllers\ReactController.jsx -> dist\server\controllers\ReactController.js
src\server\plugin\HapiWebpackHotPlugin.js -> dist\server\plugin\HapiWebpackHotPlugin.js
src\server\ServerManager.js -> dist\server\ServerManager.js
src\server.js -> dist\server.js
src\services\ProviderService.js -> dist\services\ProviderService.js
src\services\ServerService.js -> dist\services\ServerService.js
src\stores\loading\LoadingAction.js -> dist\stores\loading\LoadingAction.js
src\stores\loading\LoadingReducer.js -> dist\stores\loading\LoadingReducer.js
src\stores\meta\MetaAction.js -> dist\stores\meta\MetaAction.js
src\stores\meta\MetaReducer.js -> dist\stores\meta\MetaReducer.js
src\stores\render\RenderReducer.js -> dist\stores\render\RenderReducer.js
src\stores\rootReducer.js -> dist\stores\rootReducer.js
src\stores\rootSaga.js -> dist\stores\rootSaga.js
src\stores\user\UserAction.js -> dist\stores\user\UserAction.js
src\stores\user\UserReducer.js -> dist\stores\user\UserReducer.js
src\stores\user\UserSaga.js -> dist\stores\user\UserSaga.js
src\views\about\About.jsx -> dist\views\about\About.js
src\views\about\AboutAsync.jsx -> dist\views\about\AboutAsync.js
src\views\contact\Contact.jsx -> dist\views\contact\Contact.js
src\views\contact\ContactForm.jsx -> dist\views\contact\ContactForm.js
src\views\errors\NotFound.jsx -> dist\views\errors\NotFound.js
src\views\errors\NotFoundAsync.jsx -> dist\views\errors\NotFoundAsync.js
src\views\home\Home.jsx -> dist\views\home\Home.js
src\views\landmarks\Footer.jsx -> dist\views\landmarks\Footer.js
src\views\landmarks\FooterAsync.jsx -> dist\views\landmarks\FooterAsync.js
src\views\landmarks\Header.jsx -> dist\views\landmarks\Header.js
$ cross-env npm run watchServer & npm run devServer

> hapi-react-hot-loader-example@1.0.0 watchServer D:\Work\rococode\reacthotloader
> cross-env BABEL_ENV=server ./node_modules/.bin/babel src --out-dir dist --watch

src\client.jsx -> dist\client.js
src\RouterWrapper.jsx -> dist\RouterWrapper.js
src\server\controllers\AssetsController.js -> dist\server\controllers\AssetsController.js
src\server\controllers\ReactController.jsx -> dist\server\controllers\ReactController.js
src\server\plugin\HapiWebpackHotPlugin.js -> dist\server\plugin\HapiWebpackHotPlugin.js
src\server\ServerManager.js -> dist\server\ServerManager.js
src\server.js -> dist\server.js
src\services\ProviderService.js -> dist\services\ProviderService.js
src\services\ServerService.js -> dist\services\ServerService.js
src\stores\loading\LoadingAction.js -> dist\stores\loading\LoadingAction.js
src\stores\loading\LoadingReducer.js -> dist\stores\loading\LoadingReducer.js
src\stores\meta\MetaAction.js -> dist\stores\meta\MetaAction.js
src\stores\meta\MetaReducer.js -> dist\stores\meta\MetaReducer.js
src\stores\render\RenderReducer.js -> dist\stores\render\RenderReducer.js
src\stores\rootReducer.js -> dist\stores\rootReducer.js
src\stores\rootSaga.js -> dist\stores\rootSaga.js
src\stores\user\UserAction.js -> dist\stores\user\UserAction.js
src\stores\user\UserReducer.js -> dist\stores\user\UserReducer.js
src\stores\user\UserSaga.js -> dist\stores\user\UserSaga.js
src\views\about\About.jsx -> dist\views\about\About.js
src\views\about\AboutAsync.jsx -> dist\views\about\AboutAsync.js
src\views\contact\Contact.jsx -> dist\views\contact\Contact.js
src\views\contact\ContactForm.jsx -> dist\views\contact\ContactForm.js
src\views\errors\NotFound.jsx -> dist\views\errors\NotFound.js
src\views\errors\NotFoundAsync.jsx -> dist\views\errors\NotFoundAsync.js
src\views\home\Home.jsx -> dist\views\home\Home.js
src\views\landmarks\Footer.jsx -> dist\views\landmarks\Footer.js
src\views\landmarks\FooterAsync.jsx -> dist\views\landmarks\FooterAsync.js
src\views\landmarks\Header.jsx -> dist\views\landmarks\Header.js
`

after that everything is stuck and I can't load anything on localhost:3000

any idea what is wrong?

**Comment by codeBelt** [comment] 2017-08-28 15:46
Can you give me what OS you are on and what is your node version? I haven't tested on Windows. I am on OS X El Capitan and Node v8.1.4

Can you give me more details on `everything is stuck`? What do you see on `localhost:3000`?

**Comment by n8rzz** [comment] 2017-08-28 16:05
I just built for the first time off of `master` and everything seems to be working fine with the following commands:

```
git clone
cd hapi-react-hot-loader-example
yarn
yarn dev
```

OSX
node: 7.0.0
npm: 3.10.8

**Comment by rocodesign** [comment] 2017-08-28 16:10
Hi
Thanks for the response
I am on Windows 7

node: 6.9.5
npm: 3.10.10
yarn v0.24.4

nothing loads, 
I've got no error
![image](https://user-images.githubusercontent.com/254110/29782234-7480e360-8c24-11e7-98ef-376913bf0c60.png)

![image](https://user-images.githubusercontent.com/254110/29782253-884932c6-8c24-11e7-8c5c-65b616fd5f5c.png)

**Comment by rocodesign** [comment] 2017-08-28 16:15
production build works fine though

**Comment by n8rzz** [comment] 2017-08-28 16:39
@rocodesign for the screenshots, it doesn't look like the server starts?  At the end of the output your should see the line: `Server running in development mode at: http://localhost:3000
`

<img width="1198" alt="screen shot 2017-08-28 at 11 37 44 am" src="https://user-images.githubusercontent.com/3325985/29783303-71071acc-8be5-11e7-8491-2b10eb32fb1c.png">

**Comment by n8rzz** [comment] 2017-08-28 16:39
the above is the result of `npm run dev` or `yard dev`

**Comment by codeBelt** [comment] 2017-08-28 16:44
Windows has a hard time with the single `&` for parallel executions. Its to do with `"dev": "cross-env npm run watchServer & npm run devServer",`. 

Thanks, we will look into it.

**Comment by rocodesign** [comment] 2017-08-28 17:03
both 'yarn dev' and 'npm run dev' produce the same result.

I also tried replacing the single & with a double && but had the same result.
as a workaround running 
"npm run watchServer" and "npm run devServer" in two separate terminals works fine. I guess it can be considered a node/npm bug so I'm closing it.

**Comment by codeBelt** [comment] 2017-08-28 17:11
Reopening because this is something I would like to figure out.

**Comment by codeBelt** [comment] 2017-08-31 18:30
@rocodesign can you test out the [fix/dev-task-windows](https://github.com/codeBelt/hapi-react-hot-loader-example/tree/fix/dev-task-windows) branch and see if it fixes the issue for you.

**Comment by codeBelt** [comment] 2017-09-01 03:22
@rocodesign change of plan. I confirmed with someone else. Check out master because I merged it in. Reopen this issue if it doesn't work.

**Closed as completed by codeBelt** 2017-09-01 03:22 UTC
Labels: bug, help wanted
